# Generated by Django 5.2 on 2025-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioposition',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount invested (alternative to specifying quantity)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioposition',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
