# Generated by Django 5.2 on 2025-05-07 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_logic', '0002_portfolioposition_total_investment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='price_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this price data was recorded'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['-price_timestamp'], name='stock_logic_price_t_2b1154_idx'),
        ),
    ]
