# Generated by Django 5.2 on 2025-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_logic', '0004_industry_sector_stock_description_stock_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_name',
            field=models.CharField(blank=True, help_text='A shorter name for display in charts and legends', max_length=25, null=True),
        ),
    ]
