# Generated by Django 5.2 on 2025-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_logic', '0005_portfolio_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current portfolio value', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial portfolio value when created', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stored_initial_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial value calculated once and stored', max_digits=15, null=True),
        ),
    ]
